erDiagram
    Order ||--o{ OrderDetails : contains
    OrderDetails }o--|| Item : "contains item"
    Item }o--|| ProductType : "has product type"
    ProductType }o--|| StatusDefinition : "has status definitions"

    Order {
        int id
        int orderNumber
        date orderDate
        decimal totalAmount
    }

    OrderDetails {
        int id
        int order_id
        int item_id
        int quantity
        decimal price
    }

    Item {
        int id
        string name
        string description
        decimal price
        int productType_id
    }

    ProductType {
        int id
        string name
        Long[] differentSteps
    }

    StatusDefinition {
        int id
        string name
        string description
        string image
    }
