version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./backend/src:/app/src
      - ./backend/target:/app/target
      - ./.env:/app/.env
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=secret
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /app/src
        - path: ./backend/pom.xml
          action: rebuild

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
      - ./frontend/package.json:/app/package.json
      - ./frontend/svelte.config.js:/app/svelte.config.js
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /app/src
        - path: ./frontend/package.json
          action: rebuild
